version: "3.1"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-task-manager
    restart: always
    ports:
      - 1000:80
    volumes:
      - /sessions
