version: '3.1'

services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
      - PMA_ARBITRARY=1
      restart: always
      ports:
      - 1000:80
      volumes:
      - /sessions